In [4]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [1]:
from pathlib import Path

PROJECT_DIR = Path(
    "/content/drive/MyDrive/Imagined_Speech_EEG_Project"
)

DATA_DIR = PROJECT_DIR / "dataset"

print("Project folder exists:", PROJECT_DIR.exists())
print("Dataset folder exists:", DATA_DIR.exists())

Project folder exists: False
Dataset folder exists: False

In [6]:
mat_files = sorted(DATA_DIR.rglob("*.mat"))

print("Number of MATLAB files:", len(mat_files))

for i, file in enumerate(mat_files, 1):
    print(i, file.name)

Number of MATLAB files: 45
1 Data_Sample01.mat
2 Data_Sample02.mat
3 Data_Sample03.mat
4 Data_Sample04.mat
5 Data_Sample05.mat
6 Data_Sample06.mat
7 Data_Sample07.mat
8 Data_Sample08.mat
9 Data_Sample09.mat
10 Data_Sample10.mat
11 Data_Sample11.mat
12 Data_Sample12.mat
13 Data_Sample13.mat
14 Data_Sample14.mat
15 Data_Sample15.mat
16 Data_Sample01.mat
17 Data_Sample02.mat
18 Data_Sample03.mat
19 Data_Sample04.mat
20 Data_Sample05.mat
21 Data_Sample06.mat
22 Data_Sample07.mat
23 Data_Sample08.mat
24 Data_Sample09.mat
25 Data_Sample10.mat
26 Data_Sample11.mat
27 Data_Sample12.mat
28 Data_Sample13.mat
29 Data_Sample14.mat
30 Data_Sample15.mat
31 Data_Sample01.mat
32 Data_Sample02.mat
33 Data_Sample03.mat
34 Data_Sample04.mat
35 Data_Sample05.mat
36 Data_Sample06.mat
37 Data_Sample07.mat
38 Data_Sample08.mat
39 Data_Sample09.mat
40 Data_Sample10.mat
41 Data_Sample11.mat
42 Data_Sample12.mat
43 Data_Sample13.mat
44 Data_Sample14.mat
45 Data_Sample15.mat

In [5]:
from pathlib import Path

MYDRIVE = Path("/content/drive/MyDrive")

print("Top-level folders in My Drive:")
for item in MYDRIVE.iterdir():
    print(item)

Top-level folders in My Drive:
/content/drive/MyDrive/Colab Notebooks
/content/drive/MyDrive/Swetha Varghese .jpg
/content/drive/MyDrive/Swetha Varghese.jpg
/content/drive/MyDrive/Documents
/content/drive/MyDrive/New aadhar .pdf
/content/drive/MyDrive/Random
/content/drive/MyDrive/Jee mains 2023
/content/drive/MyDrive/Screenshot_20230321-124904.png
/content/drive/MyDrive/Screenshot_20230321-124919.png
/content/drive/MyDrive/Classroom
/content/drive/MyDrive/ece_66_swetha varghese (1).pdf
/content/drive/MyDrive/ece_66_swetha varghese.pdf
/content/drive/MyDrive/ece_66_swetha varghese_compressed.pdf
/content/drive/MyDrive/ece_66_swetha varghese_compressed (1).pdf
/content/drive/MyDrive/b161bbb3-308d-4709-8229-0a2fd742cbe5_1710332309%20-%2030.00%20To%20Shwetha%20Mathew%20on%20Google%20Pay.png
/content/drive/MyDrive/Screenshot_20240326-225851.png
/content/drive/MyDrive/S2 VDT 2019 SCHEME UNIVERSITY QUESTIONS.pdf
/content/drive/MyDrive/Maths.pdf
/content/drive/MyDrive/module 5 maths.pdf
/content/drive/MyDrive/MAT102 Q BANK .pdf
/content/drive/MyDrive/module 1 maths.pdf
/content/drive/MyDrive/module 3 & 4 maths (1).pdf
/content/drive/MyDrive/module 3 & 4 maths.pdf
/content/drive/MyDrive/D&E Module1-detailed.gdoc
/content/drive/MyDrive/910c9ec9-86cc-4c0e-9195-e35f0361e6be_payment_confirmation_202408227-103434.png
/content/drive/MyDrive/WhatsApp Image 2024-08-17 at 19.35.04_730ffc44.jpg
/content/drive/MyDrive/mesh-node-analysis.pdf
/content/drive/MyDrive/Design Engineering Assignment.pdf
/content/drive/MyDrive/Swetha Varghese.pdf
/content/drive/MyDrive/SSD_Module_3 - PN Junction.gdoc
/content/drive/MyDrive/maths assignment.pdf
/content/drive/MyDrive/DOC-20241215-WA0027. (1).pdf
/content/drive/MyDrive/DOC-20241215-WA0027..pdf
/content/drive/MyDrive/49867fa2-cf5c-4619-849e-cf05d6b28279_payment_confirmation_20250129-093521.png
/content/drive/MyDrive/Can you give the output in each stage.gdoc
/content/drive/MyDrive/DOC-20250413-WA0021..pdf
/content/drive/MyDrive/963886713S4ECEQB202226Batch_copy.pdf
/content/drive/MyDrive/ECT202 ANALOG CIRCUITS, JUNE 2023_copy.pdf
/content/drive/MyDrive/MAT204 PROBABILITY, RANDOM PROCESSES AND NUMERICAL METHODS, JUNE 2023_copy (1).pdf
/content/drive/MyDrive/rohini_91175795696_copy.pdf
/content/drive/MyDrive/MAT204 PROBABILITY, RANDOM PROCESSES AND NUMERICAL METHODS, JUNE 2023_copy.pdf
/content/drive/MyDrive/Electronic Devices and Circuit Theory_copy.pdf
/content/drive/MyDrive/Autonomous Vehicle Sensor Fusion - Claude.pdf
/content/drive/MyDrive/custom_messages.txt
/content/drive/MyDrive/ros2_ws.zip
/content/drive/MyDrive/Untitled document (16).gdoc
/content/drive/MyDrive/Untitled document (15).gdoc
/content/drive/MyDrive/IMG-20250202-WA0069.jpg
/content/drive/MyDrive/Screenshot_2025-07-16-11-29-41-164_com.google.android.apps.nbu.paisa.user.jpg
/content/drive/MyDrive/payment_confirmation_202507212-110830.png
/content/drive/MyDrive/execom_selection_task.pdf
/content/drive/MyDrive/Untitled document (14).gdoc
/content/drive/MyDrive/IMG_20250925_082504.png
/content/drive/MyDrive/ATTENDENCE AUGUST.xlsx
/content/drive/MyDrive/Untitled document (13).gdoc
/content/drive/MyDrive/Untitled form (File responses)
/content/drive/MyDrive/Untitled form (1).gform
/content/drive/MyDrive/DOC-20260128-WA0012 (1).xlsx
/content/drive/MyDrive/DOC-20260128-WA0012.xlsx
/content/drive/MyDrive/DOC-20260402-WA0001.docx
/content/drive/MyDrive/Untitled document (12).gdoc
/content/drive/MyDrive/baja video
/content/drive/MyDrive/VID_20260607_003113.mp4
/content/drive/MyDrive/VID_20260607_003014.mp4
/content/drive/MyDrive/VID_20260607_002942.mp4
/content/drive/MyDrive/IMG-20260606-WA0064(1).jpg
/content/drive/MyDrive/Phase2_evaluation
/content/drive/MyDrive/Untitled spreadsheet (1).gsheet
/content/drive/MyDrive/Untitled document (11).gdoc
/content/drive/MyDrive/Untitled document (10).gdoc
/content/drive/MyDrive/FUND DECODED.gsheet
/content/drive/MyDrive/Untitled document (9).gdoc
/content/drive/MyDrive/Untitled document (8).gdoc
/content/drive/MyDrive/Untitled document (7).gdoc
/content/drive/MyDrive/Placement training feedback - DAY 1 (Responses).gsheet
/content/drive/MyDrive/Placement training feedback - DAY 1.gform
/content/drive/MyDrive/Untitled document (6).gdoc
/content/drive/MyDrive/Untitled form.gform
/content/drive/MyDrive/Untitled document (5).gdoc
/content/drive/MyDrive/Untitled document (4).gdoc
/content/drive/MyDrive/Untitled document (3).gdoc
/content/drive/MyDrive/UCIe_Seminar_Topic_and_Title-1 (1).gdoc
/content/drive/MyDrive/UCIe_Seminar_Topic_and_Title-1.gdoc
/content/drive/MyDrive/Untitled document (2).gdoc
/content/drive/MyDrive/Untitled document (1).gdoc
/content/drive/MyDrive/Untitled document.gdoc
/content/drive/MyDrive/VID-20260814-WA0010(2).mp4
/content/drive/MyDrive/Cgpc
/content/drive/MyDrive/Cgpc students list.gsheet
/content/drive/MyDrive/Cgpc students list.xlsx
/content/drive/MyDrive/1789374060 - 600.00 To A017_Gauri Luxmi_ on Google Pay.png
/content/drive/MyDrive/EEG Imagined Speech Reference Papers.gdoc
/content/drive/MyDrive/IEEE Literature Review and Research Gaps in EEG Im....gdoc
/content/drive/MyDrive/Untitled spreadsheet.gsheet
/content/drive/MyDrive/Swetha_Varghese_Resume_1 (2)_compressed.pdf
/content/drive/MyDrive/eeg-imagined-speech.zip
/content/drive/MyDrive/eeg_data
/content/drive/MyDrive/eeg_results
/content/drive/MyDrive/Imagined_Speech_EEG_Project

In [7]:
from pathlib import Path

mat_files = sorted(MYDRIVE.rglob("*.mat"))

print("Total MATLAB files:", len(mat_files))
print()

for i, file in enumerate(mat_files, 1):
    print(i, "->", file)

Total MATLAB files: 90

1 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Test set/Data_Sample01.mat
2 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Test set/Data_Sample02.mat
3 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Test set/Data_Sample03.mat
4 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Test set/Data_Sample04.mat
5 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Test set/Data_Sample05.mat
6 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Test set/Data_Sample06.mat
7 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Test set/Data_Sample07.mat
8 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Test set/Data_Sample08.mat
9 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Test set/Data_Sample09.mat
10 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Test set/Data_Sample10.mat
11 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Test set/Data_Sample11.mat
12 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Test set/Data_Sample12.mat
13 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Test set/Data_Sample13.mat
14 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Test set/Data_Sample14.mat
15 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Test set/Data_Sample15.mat
16 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Training set/Data_Sample01.mat
17 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Training set/Data_Sample02.mat
18 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Training set/Data_Sample03.mat
19 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Training set/Data_Sample04.mat
20 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Training set/Data_Sample05.mat
21 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Training set/Data_Sample06.mat
22 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Training set/Data_Sample07.mat
23 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Training set/Data_Sample08.mat
24 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Training set/Data_Sample09.mat
25 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Training set/Data_Sample10.mat
26 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Training set/Data_Sample11.mat
27 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Training set/Data_Sample12.mat
28 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Training set/Data_Sample13.mat
29 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Training set/Data_Sample14.mat
30 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Training set/Data_Sample15.mat
31 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Validation set/Data_Sample01.mat
32 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Validation set/Data_Sample02.mat
33 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Validation set/Data_Sample03.mat
34 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Validation set/Data_Sample04.mat
35 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Validation set/Data_Sample05.mat
36 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Validation set/Data_Sample06.mat
37 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Validation set/Data_Sample07.mat
38 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Validation set/Data_Sample08.mat
39 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Validation set/Data_Sample09.mat
40 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Validation set/Data_Sample10.mat
41 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Validation set/Data_Sample11.mat
42 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Validation set/Data_Sample12.mat
43 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Validation set/Data_Sample13.mat
44 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Validation set/Data_Sample14.mat
45 -> /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Validation set/Data_Sample15.mat
46 -> /content/drive/MyDrive/eeg_data/Test set/Data_Sample01.mat
47 -> /content/drive/MyDrive/eeg_data/Test set/Data_Sample02.mat
48 -> /content/drive/MyDrive/eeg_data/Test set/Data_Sample03.mat
49 -> /content/drive/MyDrive/eeg_data/Test set/Data_Sample04.mat
50 -> /content/drive/MyDrive/eeg_data/Test set/Data_Sample05.mat
51 -> /content/drive/MyDrive/eeg_data/Test set/Data_Sample06.mat
52 -> /content/drive/MyDrive/eeg_data/Test set/Data_Sample07.mat
53 -> /content/drive/MyDrive/eeg_data/Test set/Data_Sample08.mat
54 -> /content/drive/MyDrive/eeg_data/Test set/Data_Sample09.mat
55 -> /content/drive/MyDrive/eeg_data/Test set/Data_Sample10.mat
56 -> /content/drive/MyDrive/eeg_data/Test set/Data_Sample11.mat
57 -> /content/drive/MyDrive/eeg_data/Test set/Data_Sample12.mat
58 -> /content/drive/MyDrive/eeg_data/Test set/Data_Sample13.mat
59 -> /content/drive/MyDrive/eeg_data/Test set/Data_Sample14.mat
60 -> /content/drive/MyDrive/eeg_data/Test set/Data_Sample15.mat
61 -> /content/drive/MyDrive/eeg_data/Training set/Data_Sample01.mat
62 -> /content/drive/MyDrive/eeg_data/Training set/Data_Sample02.mat
63 -> /content/drive/MyDrive/eeg_data/Training set/Data_Sample03.mat
64 -> /content/drive/MyDrive/eeg_data/Training set/Data_Sample04.mat
65 -> /content/drive/MyDrive/eeg_data/Training set/Data_Sample05.mat
66 -> /content/drive/MyDrive/eeg_data/Training set/Data_Sample06.mat
67 -> /content/drive/MyDrive/eeg_data/Training set/Data_Sample07.mat
68 -> /content/drive/MyDrive/eeg_data/Training set/Data_Sample08.mat
69 -> /content/drive/MyDrive/eeg_data/Training set/Data_Sample09.mat
70 -> /content/drive/MyDrive/eeg_data/Training set/Data_Sample10.mat
71 -> /content/drive/MyDrive/eeg_data/Training set/Data_Sample11.mat
72 -> /content/drive/MyDrive/eeg_data/Training set/Data_Sample12.mat
73 -> /content/drive/MyDrive/eeg_data/Training set/Data_Sample13.mat
74 -> /content/drive/MyDrive/eeg_data/Training set/Data_Sample14.mat
75 -> /content/drive/MyDrive/eeg_data/Training set/Data_Sample15.mat
76 -> /content/drive/MyDrive/eeg_data/Validation set/Data_Sample01.mat
77 -> /content/drive/MyDrive/eeg_data/Validation set/Data_Sample02.mat
78 -> /content/drive/MyDrive/eeg_data/Validation set/Data_Sample03.mat
79 -> /content/drive/MyDrive/eeg_data/Validation set/Data_Sample04.mat
80 -> /content/drive/MyDrive/eeg_data/Validation set/Data_Sample05.mat
81 -> /content/drive/MyDrive/eeg_data/Validation set/Data_Sample06.mat
82 -> /content/drive/MyDrive/eeg_data/Validation set/Data_Sample07.mat
83 -> /content/drive/MyDrive/eeg_data/Validation set/Data_Sample08.mat
84 -> /content/drive/MyDrive/eeg_data/Validation set/Data_Sample09.mat
85 -> /content/drive/MyDrive/eeg_data/Validation set/Data_Sample10.mat
86 -> /content/drive/MyDrive/eeg_data/Validation set/Data_Sample11.mat
87 -> /content/drive/MyDrive/eeg_data/Validation set/Data_Sample12.mat
88 -> /content/drive/MyDrive/eeg_data/Validation set/Data_Sample13.mat
89 -> /content/drive/MyDrive/eeg_data/Validation set/Data_Sample14.mat
90 -> /content/drive/MyDrive/eeg_data/Validation set/Data_Sample15.mat

In [8]:
from scipy.io import loadmat
import numpy as np

mat_path = Path(
    "/content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Training set/Data_Sample01.mat"
)

print("Inspecting:")
print(mat_path)
print()

data = loadmat(
    str(mat_path),
    squeeze_me=True,
    struct_as_record=False
)

print("Variables inside the MATLAB file:")

for key, value in data.items():
    if not key.startswith("__"):
        print("\n-----------------------------")
        print("Variable:", key)
        print("Type:", type(value))

        if isinstance(value, np.ndarray):
            print("Shape:", value.shape)
            print("Dtype:", value.dtype)

        if hasattr(value, "_fieldnames"):
            print("Fields:", value._fieldnames)

Inspecting:
/content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset/Training set/Data_Sample01.mat

Variables inside the MATLAB file:

-----------------------------
Variable: epo_train
Type: <class 'scipy.io.matlab._mio5_params.mat_struct'>
Fields: ['clab', 'fs', 'title', 'file', 'x', 'y', 't', 'className']

-----------------------------
Variable: mnt
Type: <class 'scipy.io.matlab._mio5_params.mat_struct'>
Fields: ['x', 'y', 'pos_3d', 'clab']

In [9]:
epo = data["epo_train"]

print("=== epo_train ===")

for field in epo._fieldnames:
    value = getattr(epo, field)

    print("\n-----------------------------")
    print("Field:", field)
    print("Type:", type(value))

    if isinstance(value, np.ndarray):
        print("Shape:", value.shape)
        print("Dtype:", value.dtype)

    else:
        print("Value:", value)

=== epo_train ===

-----------------------------
Field: clab
Type: <class 'numpy.ndarray'>
Shape: (64,)
Dtype: object

-----------------------------
Field: fs
Type: <class 'int'>
Value: 256

-----------------------------
Field: title
Type: <class 'str'>
Value: sub1

-----------------------------
Field: file
Type: <class 'str'>
Value: sub1

-----------------------------
Field: x
Type: <class 'numpy.ndarray'>
Shape: (795, 64, 300)
Dtype: float64

-----------------------------
Field: y
Type: <class 'numpy.ndarray'>
Shape: (5, 300)
Dtype: uint8

-----------------------------
Field: t
Type: <class 'numpy.ndarray'>
Shape: (795,)
Dtype: float64

-----------------------------
Field: className
Type: <class 'numpy.ndarray'>
Shape: (5,)
Dtype: object

In [10]:
# Inspect class names
print("CLASS NAMES:")
for i, name in enumerate(epo.className):
    print(i, ":", name)

# Inspect electrode names
print("\nNUMBER OF ELECTRODES:", len(epo.clab))
print("\nELECTRODE NAMES:")
for i, channel in enumerate(epo.clab):
    print(i, ":", channel)

# Inspect label matrix
print("\nLABEL MATRIX SHAPE:", epo.y.shape)

print("\nSUM OF EACH LABEL ROW:")
print(epo.y.sum(axis=1))

print("\nSUM OF EACH TRIAL COLUMN (first 20):")
print(epo.y.sum(axis=0)[:20])

# Inspect time information
print("\nTIME VECTOR:")
print("First 10 values:", epo.t[:10])
print("Last 10 values:", epo.t[-10:])
print("Duration in seconds:", len(epo.t) / epo.fs)

# Check signal values
print("\nEEG DATA:")
print("Minimum:", np.min(epo.x))
print("Maximum:", np.max(epo.x))
print("Mean:", np.mean(epo.x))
print("NaN values:", np.isnan(epo.x).sum())

CLASS NAMES:
0 : Hello
1 : Helpme
2 : Stop
3 : Thankyou
4 : Yes

NUMBER OF ELECTRODES: 64

ELECTRODE NAMES:
0 : Fp1
1 : Fp2
2 : F7
3 : F3
4 : Fz
5 : F4
6 : F8
7 : FC5
8 : FC1
9 : FC2
10 : FC6
11 : T7
12 : C3
13 : Cz
14 : C4
15 : T8
16 : TP9
17 : CP5
18 : CP1
19 : CP2
20 : CP6
21 : TP10
22 : P7
23 : P3
24 : Pz
25 : P4
26 : P8
27 : PO9
28 : O1
29 : Oz
30 : O2
31 : PO10
32 : AF7
33 : AF3
34 : AF4
35 : AF8
36 : F5
37 : F1
38 : F2
39 : F6
40 : FT9
41 : FT7
42 : FC3
43 : FC4
44 : FT8
45 : FT10
46 : C5
47 : C1
48 : C2
49 : C6
50 : TP7
51 : CP3
52 : CPz
53 : CP4
54 : TP8
55 : P5
56 : P1
57 : P2
58 : P6
59 : PO7
60 : PO3
61 : POz
62 : PO4
63 : PO8

LABEL MATRIX SHAPE: (5, 300)

SUM OF EACH LABEL ROW:
[60 60 60 60 60]

SUM OF EACH TRIAL COLUMN (first 20):
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

TIME VECTOR:
First 10 values: [-500.      -496.09375 -492.1875  -488.28125 -484.375   -480.46875
 -476.5625  -472.65625 -468.75    -464.84375]
Last 10 values: [2566.40625 2570.3125  2574.21875 2578.125   2582.03125 2585.9375
 2589.84375 2593.75    2597.65625 2601.5625 ]
Duration in seconds: 3.10546875

EEG DATA:
Minimum: -1472.8496986455004
Maximum: 670.7183476453647
Mean: 24.443299749212816
NaN values: 0

In [11]:
from pathlib import Path
from scipy.io import loadmat
import numpy as np
import pandas as pd

base = Path(
    "/content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset"
)

splits = ["Training set", "Validation set", "Test set"]

results = []

for split in splits:

    for subject_num in range(1, 16):

        filename = f"Data_Sample{subject_num:02d}.mat"
        file_path = base / split / filename

        mat = loadmat(
            str(file_path),
            squeeze_me=True,
            struct_as_record=False
        )

        epo = mat["epo_train"]

        # Convert one-hot labels into class indices
        labels = np.argmax(epo.y, axis=0)

        results.append({
            "Split": split,
            "Subject": subject_num,
            "EEG Shape": epo.x.shape,
            "Trials": epo.x.shape[2],
            "Sampling Rate": epo.fs,
            "Class Counts": np.bincount(labels, minlength=5).tolist()
        })

df = pd.DataFrame(results)

print(df.to_string(index=False))

KeyError: 'epo_train'

In [12]:
from pathlib import Path
from scipy.io import loadmat

base = Path(
    "/content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset"
)

splits = ["Training set", "Validation set", "Test set"]

for split in splits:
    print("\n==========", split, "==========")

    for subject_num in range(1, 16):

        filename = f"Data_Sample{subject_num:02d}.mat"
        file_path = base / split / filename

        mat = loadmat(
            str(file_path),
            squeeze_me=True,
            struct_as_record=False
        )

        variables = [
            key for key in mat.keys()
            if not key.startswith("__")
        ]

        if "epo_train" in mat:
            epo = mat["epo_train"]
            print(
                filename,
                "| epo_train found |",
                "Shape:", epo.x.shape
            )
        else:
            print(
                filename,
                "| MISSING epo_train | Variables:",
                variables
            )

========== Training set ==========
Data_Sample01.mat | epo_train found | Shape: (795, 64, 300)
Data_Sample02.mat | epo_train found | Shape: (795, 64, 300)
Data_Sample03.mat | epo_train found | Shape: (795, 64, 300)
Data_Sample04.mat | epo_train found | Shape: (795, 64, 300)
Data_Sample05.mat | epo_train found | Shape: (795, 64, 300)
Data_Sample06.mat | epo_train found | Shape: (795, 64, 300)
Data_Sample07.mat | epo_train found | Shape: (795, 64, 300)
Data_Sample08.mat | epo_train found | Shape: (795, 64, 300)
Data_Sample09.mat | epo_train found | Shape: (795, 64, 300)
Data_Sample10.mat | epo_train found | Shape: (795, 64, 300)
Data_Sample11.mat | epo_train found | Shape: (795, 64, 300)
Data_Sample12.mat | epo_train found | Shape: (795, 64, 300)
Data_Sample13.mat | epo_train found | Shape: (795, 64, 300)
Data_Sample14.mat | epo_train found | Shape: (795, 64, 300)
Data_Sample15.mat | epo_train found | Shape: (795, 64, 300)

========== Validation set ==========
Data_Sample01.mat | MISSING epo_train | Variables: ['epo_validation', 'mnt']
Data_Sample02.mat | MISSING epo_train | Variables: ['epo_validation', 'mnt']
Data_Sample03.mat | MISSING epo_train | Variables: ['epo_validation', 'mnt']
Data_Sample04.mat | MISSING epo_train | Variables: ['epo_validation', 'mnt']
Data_Sample05.mat | MISSING epo_train | Variables: ['epo_validation', 'mnt']
Data_Sample06.mat | MISSING epo_train | Variables: ['epo_validation', 'mnt']
Data_Sample07.mat | MISSING epo_train | Variables: ['epo_validation', 'mnt']
Data_Sample08.mat | MISSING epo_train | Variables: ['epo_validation', 'mnt']
Data_Sample09.mat | MISSING epo_train | Variables: ['epo_validation', 'mnt']
Data_Sample10.mat | MISSING epo_train | Variables: ['epo_validation', 'mnt']
Data_Sample11.mat | MISSING epo_train | Variables: ['epo_validation', 'mnt']
Data_Sample12.mat | MISSING epo_train | Variables: ['epo_validation', 'mnt']
Data_Sample13.mat | MISSING epo_train | Variables: ['epo_validation', 'mnt']
Data_Sample14.mat | MISSING epo_train | Variables: ['epo_validation', 'mnt']
Data_Sample15.mat | MISSING epo_train | Variables: ['epo_validation', 'mnt']

========== Test set ==========

NotImplementedError: Please use HDF reader for matlab v7.3 files, e.g. h5py

In [13]:
!pip install h5py

Requirement already satisfied: h5py in /usr/local/lib/python3.13/dist-packages (3.14.0)
Requirement already satisfied: numpy>=1.19.3 in /usr/local/lib/python3.13/dist-packages (from h5py) (2.1.3)

In [14]:
import h5py

test_path = (
    "/content/drive/MyDrive/Imagined_Speech_EEG_Project/"
    "dataset/Test set/Data_Sample01.mat"
)

with h5py.File(test_path, "r") as f:

    print("Variables inside test file:")

    def inspect(name, obj):
        if isinstance(obj, h5py.Dataset):
            print(
                "Dataset:", name,
                "| Shape:", obj.shape,
                "| Dtype:", obj.dtype
            )
        elif isinstance(obj, h5py.Group):
            print("Group:", name)

    f.visititems(inspect)

Variables inside test file:
Group: #refs#
Dataset: #refs#/0 | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/0b | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/1 | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/1b | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/2 | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/2b | Shape: (4, 1) | Dtype: uint16
Dataset: #refs#/3 | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/3b | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/4 | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/4b | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/5 | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/5b | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/6 | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/6b | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/7 | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/7b | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/8 | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/8b | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/9 | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/9b | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/A | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/Ab | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/B | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/Bb | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/C | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/Cb | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/D | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/Db | Shape: (4, 1) | Dtype: uint16
Dataset: #refs#/E | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/Eb | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/F | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/Fb | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/G | Shape: (4, 1) | Dtype: uint16
Dataset: #refs#/Gb | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/H | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/Hb | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/I | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/Ib | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/J | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/Jb | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/K | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/Kb | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/L | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/Lb | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/M | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/Mb | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/N | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/Nb | Shape: (4, 1) | Dtype: uint16
Dataset: #refs#/O | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/Ob | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/P | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/Pb | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/Q | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/Qb | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/R | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/Rb | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/S | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/Sb | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/T | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/Tb | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/U | Shape: (4, 1) | Dtype: uint16
Dataset: #refs#/Ub | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/V | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/Vb | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/W | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/Wb | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/X | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/Xb | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/Y | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/Yb | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/Z | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/Zb | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/a | Shape: (2,) | Dtype: uint64
Dataset: #refs#/ab | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/ac | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/b | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/bb | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/bc | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/c | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/cb | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/cc | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/d | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/db | Shape: (5, 1) | Dtype: uint16
Dataset: #refs#/dc | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/e | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/eb | Shape: (6, 1) | Dtype: uint16
Dataset: #refs#/ec | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/f | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/fb | Shape: (4, 1) | Dtype: uint16
Dataset: #refs#/fc | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/g | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/gb | Shape: (8, 1) | Dtype: uint16
Dataset: #refs#/gc | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/h | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/hb | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/hc | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/i | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/ib | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/ic | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/j | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/jb | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/jc | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/k | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/kb | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/l | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/lb | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/m | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/mb | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/n | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/nb | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/o | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/ob | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/p | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/pb | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/q | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/qb | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/r | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/rb | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/s | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/sb | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/t | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/tb | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/u | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/ub | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/v | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/vb | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/w | Shape: (4, 1) | Dtype: uint16
Dataset: #refs#/wb | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/x | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/xb | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/y | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/yb | Shape: (3, 1) | Dtype: uint16
Dataset: #refs#/z | Shape: (2, 1) | Dtype: uint16
Dataset: #refs#/zb | Shape: (3, 1) | Dtype: uint16
Group: epo_test
Dataset: epo_test/clab | Shape: (64, 1) | Dtype: object
Dataset: epo_test/className | Shape: (5, 1) | Dtype: object
Dataset: epo_test/file | Shape: (4, 1) | Dtype: uint16
Dataset: epo_test/fs | Shape: (1, 1) | Dtype: float64
Dataset: epo_test/t | Shape: (795, 1) | Dtype: float64
Dataset: epo_test/title | Shape: (4, 1) | Dtype: uint16
Dataset: epo_test/x | Shape: (50, 64, 795) | Dtype: float64
Dataset: epo_test/y | Shape: (2,) | Dtype: uint64
Group: mnt
Dataset: mnt/clab | Shape: (64, 1) | Dtype: object
Dataset: mnt/pos_3d | Shape: (64, 3) | Dtype: float64
Dataset: mnt/x | Shape: (1, 64) | Dtype: float64
Dataset: mnt/y | Shape: (1, 64) | Dtype: float64

In [15]:
validation_path = (
    "/content/drive/MyDrive/Imagined_Speech_EEG_Project/"
    "dataset/Validation set/Data_Sample01.mat"
)

val_data = loadmat(
    validation_path,
    squeeze_me=True,
    struct_as_record=False
)

epo_val = val_data["epo_validation"]

print("Validation subject:", epo_val.title)
print("EEG shape:", epo_val.x.shape)
print("Label shape:", epo_val.y.shape)
print("Sampling frequency:", epo_val.fs)
print("Classes:", epo_val.className)

Validation subject: sub1
EEG shape: (795, 64, 50)
Label shape: (5, 50)
Sampling frequency: 256
Classes: ['Hello' 'Helpme' 'Stop' 'Thankyou' 'Yes']

In [19]:
import numpy as np
import h5py
from scipy.io import loadmat
from pathlib import Path

BASE_DIR = Path(
    "/content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset"
)

SPLIT_INFO = {
    "Training set": ("epo_train", "scipy"),
    "Validation set": ("epo_validation", "scipy"),
    "Test set": ("epo_test", "hdf5")
}

CLASS_NAMES = [
    "Hello",
    "Helpme",
    "Stop",
    "Thankyou",
    "Yes"
]


def load_eeg_file(file_path, split):

    variable_name, file_format = SPLIT_INFO[split]

    # Training and validation: MATLAB v5
    if file_format == "scipy":

        mat = loadmat(
            str(file_path),
            squeeze_me=True,
            struct_as_record=False
        )

        epo = mat[variable_name]

        # Original shape: time x channels x trials
        X = np.asarray(epo.x, dtype=np.float32)
        y_matrix = np.asarray(epo.y)

        fs = epo.fs
        channels = np.asarray(epo.clab)
        class_names = np.asarray(epo.className)

        # Convert to trials x channels x time
        X = np.transpose(X, (2, 1, 0))

        # Convert one-hot labels to class indices
        y = np.argmax(y_matrix, axis=0)

    # Test: MATLAB v7.3 / HDF5
    else:

        with h5py.File(file_path, "r") as f:

            group = f[variable_name]

            # HDF5 test shape: trials x channels x time
            X = np.asarray(
                group["x"],
                dtype=np.float32
            )

            # Read test labels as stored
            y_raw = np.asarray(group["y"])

            fs = float(group["fs"][0, 0])

            channels = np.asarray(group["clab"])
            class_names = np.asarray(group["className"])

            # Inspect labels before converting
            y = y_raw

    return X, y, fs, channels, class_names

In [20]:
for split in SPLIT_INFO:

    file_path = (
        BASE_DIR /
        split /
        "Data_Sample01.mat"
    )

    X, y, fs, channels, class_names = load_eeg_file(
        file_path,
        split
    )

    print("\n==============================")
    print("SPLIT:", split)
    print("EEG shape:", X.shape)
    print("Label shape:", y.shape)
    print("Sampling rate:", fs)
    print("Number of channels:", len(channels))
    print("Class names:", class_names)
    print("Label values:", y)

==============================
SPLIT: Training set
EEG shape: (300, 64, 795)
Label shape: (300,)
Sampling rate: 256
Number of channels: 64
Class names: ['Hello' 'Helpme' 'Stop' 'Thankyou' 'Yes']
Label values: [1 1 0 1 3 1 3 4 2 0 4 2 4 0 0 3 3 3 4 0 1 1 3 3 2 3 2 3 2 0 2 4 1 0 1 2 1
 0 1 0 2 2 0 1 4 1 0 2 0 0 4 4 1 2 3 2 0 4 3 3 4 1 3 2 2 1 0 3 4 4 2 2 2 1
 1 1 0 2 2 1 3 2 0 3 3 0 3 2 2 1 0 4 4 2 0 3 4 0 2 1 1 4 0 0 4 4 4 0 0 3 0
 2 0 1 1 0 1 4 0 2 1 2 1 3 0 1 4 3 3 2 2 3 4 4 1 2 4 3 0 4 2 2 0 4 1 2 0 0
 2 4 2 2 4 1 3 4 3 4 2 1 3 2 1 0 2 4 4 4 2 2 1 0 3 0 3 1 4 4 3 2 0 4 4 1 3
 1 3 3 0 3 4 4 3 4 1 3 4 2 2 1 3 0 1 0 0 0 1 4 3 1 0 2 0 4 4 3 1 3 1 2 1 2
 3 4 0 1 0 3 0 3 1 0 0 2 1 0 2 2 3 3 1 1 2 4 1 2 3 3 1 3 0 1 0 4 3 4 4 2 4
 0 4 4 1 3 3 0 3 0 1 4 2 1 3 2 0 4 3 2 0 1 1 4 0 4 2 1 3 3 4 2 0 1 2 4 2 3
 3 4 4 3]

==============================
SPLIT: Validation set
EEG shape: (50, 64, 795)
Label shape: (50,)
Sampling rate: 256
Number of channels: 64
Class names: ['Hello' 'Helpme' 'Stop' 'Thankyou' 'Yes']
Label values: [3 4 1 2 1 4 3 1 2 2 2 0 2 1 1 2 1 4 4 1 0 1 0 2 3 0 3 3 3 3 0 3 4 2 4 0 1
 4 4 0 4 1 0 2 4 3 0 0 2 3]

==============================
SPLIT: Test set
EEG shape: (50, 64, 795)
Label shape: (2,)
Sampling rate: 256.0
Number of channels: 64
Class names: [[<HDF5 object reference>]
 [<HDF5 object reference>]
 [<HDF5 object reference>]
 [<HDF5 object reference>]
 [<HDF5 object reference>]]
Label values: [0 0]

In [21]:
test_path = (
    BASE_DIR /
    "Test set" /
    "Data_Sample01.mat"
)

with h5py.File(test_path, "r") as f:

    print("Test label raw data:")
    print(f["epo_test/y"][:])

    print("\nTest label shape:")
    print(f["epo_test/y"].shape)

    print("\nTest label dtype:")
    print(f["epo_test/y"].dtype)

Test label raw data:
[0 0]

Test label shape:
(2,)

Test label dtype:
uint64

In [22]:
from pathlib import Path
from scipy.io import loadmat
import numpy as np

BASE_DIR = Path(
    "/content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset"
)

for split in ["Training set", "Validation set"]:
    print("\n", "=" * 50)
    print(split)

    for file_path in sorted((BASE_DIR / split).glob("*.mat")):
        mat = loadmat(
            str(file_path),
            squeeze_me=True,
            struct_as_record=False
        )

        variable = (
            "epo_train" if split == "Training set"
            else "epo_validation"
        )

        epo = mat[variable]
        y = np.argmax(np.asarray(epo.y), axis=0)

        counts = np.bincount(y, minlength=5)

        print(
            file_path.stem,
            "Total:", len(y),
            "Class counts:", counts
        )

 ==================================================
Training set
Data_Sample01 Total: 300 Class counts: [60 60 60 60 60]
Data_Sample02 Total: 300 Class counts: [60 60 60 60 60]
Data_Sample03 Total: 300 Class counts: [60 60 60 60 60]
Data_Sample04 Total: 300 Class counts: [60 60 60 60 60]
Data_Sample05 Total: 300 Class counts: [60 60 60 60 60]
Data_Sample06 Total: 300 Class counts: [60 60 60 60 60]
Data_Sample07 Total: 300 Class counts: [60 60 60 60 60]
Data_Sample08 Total: 300 Class counts: [60 60 60 60 60]
Data_Sample09 Total: 300 Class counts: [60 60 60 60 60]
Data_Sample10 Total: 300 Class counts: [60 60 60 60 60]
Data_Sample11 Total: 300 Class counts: [60 60 60 60 60]
Data_Sample12 Total: 300 Class counts: [60 60 60 60 60]
Data_Sample13 Total: 300 Class counts: [60 60 60 60 60]
Data_Sample14 Total: 300 Class counts: [60 60 60 60 60]
Data_Sample15 Total: 300 Class counts: [60 60 60 60 60]

 ==================================================
Validation set
Data_Sample01 Total: 50 Class counts: [10 10 10 10 10]
Data_Sample02 Total: 50 Class counts: [10 10 10 10 10]
Data_Sample03 Total: 50 Class counts: [10 10 10 10 10]
Data_Sample04 Total: 50 Class counts: [10 10 10 10 10]
Data_Sample05 Total: 50 Class counts: [10 10 10 10 10]
Data_Sample06 Total: 50 Class counts: [10 10 10 10 10]
Data_Sample07 Total: 50 Class counts: [10 10 10 10 10]
Data_Sample08 Total: 50 Class counts: [10 10 10 10 10]
Data_Sample09 Total: 50 Class counts: [10 10 10 10 10]
Data_Sample10 Total: 50 Class counts: [10 10 10 10 10]
Data_Sample11 Total: 50 Class counts: [10 10 10 10 10]
Data_Sample12 Total: 50 Class counts: [10 10 10 10 10]
Data_Sample13 Total: 50 Class counts: [10 10 10 10 10]
Data_Sample14 Total: 50 Class counts: [10 10 10 10 10]
Data_Sample15 Total: 50 Class counts: [10 10 10 10 10]

In [23]:

# ============================================================
# IMAGINED SPEECH EEG DATASET DOCUMENTATION
# Dataset inspection and descriptive statistics ONLY
# No preprocessing, no model training
# ============================================================

from pathlib import Path
from scipy.io import loadmat
import numpy as np
import pandas as pd
import h5py
import json
from datetime import datetime
from IPython.display import display, Markdown

# ------------------------------------------------------------
# 1. GOOGLE DRIVE PATHS
# ------------------------------------------------------------

from google.colab import drive
drive.mount('/content/drive')

PROJECT_DIR = Path(
    "/content/drive/MyDrive/Imagined_Speech_EEG_Project"
)

DATASET_DIR = PROJECT_DIR / "dataset"

DOC_DIR = (
    PROJECT_DIR /
    "experiment_outputs" /
    "Dataset_Documentation"
)

DOC_DIR.mkdir(parents=True, exist_ok=True)

print("Dataset directory:", DATASET_DIR)
print("Documentation directory:", DOC_DIR)

# ------------------------------------------------------------
# 2. DATASET INFORMATION
# ------------------------------------------------------------

SPLITS = {
    "Training set": "epo_train",
    "Validation set": "epo_validation",
    "Test set": "epo_test"
}

CLASS_NAMES = [
    "Hello",
    "Helpme",
    "Stop",
    "Thankyou",
    "Yes"
]

NUM_CLASSES = len(CLASS_NAMES)

# ------------------------------------------------------------
# 3. MATLAB FILE LOADER FOR DOCUMENTATION
# ------------------------------------------------------------

def load_labelled_mat(file_path, variable):
    mat = loadmat(
        str(file_path),
        squeeze_me=True,
        struct_as_record=False
    )

    epo = mat[variable]

    X = np.asarray(epo.x)
    y_matrix = np.asarray(epo.y)

    labels = np.argmax(y_matrix, axis=0)

    channels = [
        str(x) for x in np.asarray(epo.clab).tolist()
    ]

    return {
        "shape_original": X.shape,
        "labels": labels,
        "sampling_rate": float(epo.fs),
        "channels": channels,
        "class_names": [
            str(x) for x in np.asarray(epo.className).tolist()
        ],
        "time": np.asarray(epo.t)
    }


def inspect_test_mat(file_path):
    with h5py.File(file_path, "r") as f:
        group = f["epo_test"]

        return {
            "shape_original": tuple(group["x"].shape),
            "sampling_rate": float(group["fs"][0, 0]),
            "label_shape": tuple(group["y"].shape),
            "label_dtype": str(group["y"].dtype),
            "label_raw": group["y"][()].tolist(),
            "channels_shape": tuple(group["clab"].shape),
            "class_names_shape": tuple(
                group["className"].shape
            )
        }


# ------------------------------------------------------------
# 4. INSPECT ALL SUBJECT FILES
# ------------------------------------------------------------

records = []
class_records = []
subject_records = []
test_records = []

for split_name, variable_name in SPLITS.items():

    folder = DATASET_DIR / split_name

    print("\nInspecting:", split_name)

    for file_path in sorted(folder.glob("*.mat")):

        subject = file_path.stem.replace("Data_Sample", "")

        if split_name in ["Training set", "Validation set"]:

            info = load_labelled_mat(
                file_path,
                variable_name
            )

            labels = info["labels"]
            counts = np.bincount(
                labels,
                minlength=NUM_CLASSES
            )

            # Standardized dimensions for labelled files
            original_shape = info["shape_original"]

            if len(original_shape) == 3:
                trials = len(labels)
                standardized_shape = (
                    trials,
                    len(info["channels"]),
                    len(info["time"])
                )
            else:
                standardized_shape = None

            records.append({
                "Split": split_name,
                "Subject": subject,
                "Trials": len(labels),
                "Channels": len(info["channels"]),
                "Time samples": len(info["time"]),
                "Sampling rate (Hz)": info["sampling_rate"],
                "Original EEG shape": str(original_shape),
                "Standardized EEG shape": str(
                    standardized_shape
                )
            })

            subject_records.append({
                "Split": split_name,
                "Subject": subject,
                "Total trials": len(labels),
                "Hello": int(counts[0]),
                "Helpme": int(counts[1]),
                "Stop": int(counts[2]),
                "Thankyou": int(counts[3]),
                "Yes": int(counts[4])
            })

            for i, class_name in enumerate(CLASS_NAMES):
                class_records.append({
                    "Split": split_name,
                    "Subject": subject,
                    "Class": class_name,
                    "Label": i,
                    "Trial count": int(counts[i])
                })

        else:
            # Test is HDF5 in the inspected dataset.
            info = inspect_test_mat(file_path)

            test_records.append({
                "Subject": subject,
                "EEG shape stored in HDF5": str(
                    info["shape_original"]
                ),
                "Sampling rate (Hz)": info["sampling_rate"],
                "y shape": str(info["label_shape"]),
                "y dtype": info["label_dtype"],
                "y raw values": str(info["label_raw"]),
                "Channel metadata shape": str(
                    info["channels_shape"]
                ),
                "Class metadata shape": str(
                    info["class_names_shape"]
                )
            })

# ------------------------------------------------------------
# 5. CREATE DATAFRAMES
# ------------------------------------------------------------

file_summary = pd.DataFrame(records)
subject_summary = pd.DataFrame(subject_records)
class_summary = pd.DataFrame(class_records)
test_summary = pd.DataFrame(test_records)

print("\nFILE SUMMARY")
display(file_summary)

print("\nSUBJECT-WISE CLASS DISTRIBUTION")
display(subject_summary)

print("\nTEST FILE STRUCTURE")
display(test_summary)

# ------------------------------------------------------------
# 6. OVERALL DATASET SUMMARY
# ------------------------------------------------------------

overall_rows = []

for split in ["Training set", "Validation set"]:
    part = file_summary[file_summary["Split"] == split]

    overall_rows.append({
        "Split": split,
        "Subjects inspected": part["Subject"].nunique(),
        "Total trials": int(part["Trials"].sum()),
        "Channels": sorted(part["Channels"].unique().tolist()),
        "Time samples": sorted(
            part["Time samples"].unique().tolist()
        ),
        "Sampling rate (Hz)": sorted(
            part["Sampling rate (Hz)"].unique().tolist()
        )
    })

overall_summary = pd.DataFrame(overall_rows)

print("\nOVERALL SUMMARY")
display(overall_summary)

# ------------------------------------------------------------
# 7. OVERALL CLASS DISTRIBUTION
# ------------------------------------------------------------

class_totals = (
    class_summary
    .groupby(["Split", "Class", "Label"])["Trial count"]
    .sum()
    .reset_index()
)

class_pivot = class_totals.pivot(
    index="Class",
    columns="Split",
    values="Trial count"
).reset_index()

print("\nOVERALL CLASS DISTRIBUTION")
display(class_pivot)

# ------------------------------------------------------------
# 8. ELECTRODE INFORMATION
# ------------------------------------------------------------

first_training_file = sorted(
    (DATASET_DIR / "Training set").glob("*.mat")
)[0]

first_info = load_labelled_mat(
    first_training_file,
    "epo_train"
)

electrode_table = pd.DataFrame({
    "Electrode Index": range(len(first_info["channels"])),
    "Electrode Name": first_info["channels"]
})

print("\nELECTRODE INFORMATION")
display(electrode_table)

# ------------------------------------------------------------
# 9. SAVE CSV TABLES
# ------------------------------------------------------------

file_summary.to_csv(
    DOC_DIR / "file_summary.csv",
    index=False
)

subject_summary.to_csv(
    DOC_DIR / "subject_class_distribution.csv",
    index=False
)

class_summary.to_csv(
    DOC_DIR / "class_distribution_by_subject.csv",
    index=False
)

class_pivot.to_csv(
    DOC_DIR / "overall_class_distribution.csv",
    index=False
)

electrode_table.to_csv(
    DOC_DIR / "electrode_information.csv",
    index=False
)

test_summary.to_csv(
    DOC_DIR / "test_file_structure.csv",
    index=False
)

# ------------------------------------------------------------
# 10. GENERATE DETAILED MARKDOWN DOCUMENTATION
# ------------------------------------------------------------

training_total = int(
    file_summary[
        file_summary["Split"] == "Training set"
    ]["Trials"].sum()
)

validation_total = int(
    file_summary[
        file_summary["Split"] == "Validation set"
    ]["Trials"].sum()
)

training_subjects = file_summary[
    file_summary["Split"] == "Training set"
]["Subject"].nunique()

validation_subjects = file_summary[
    file_summary["Split"] == "Validation set"
]["Subject"].nunique()

report = f"""
# Imagined Speech EEG Dataset
## Dataset Description and Contents

**Documentation date:** {datetime.now().strftime("%d %B %Y")}

---

## 1. Dataset Overview

The dataset used in this project is the Imagined Speech EEG
dataset associated with the 2020 International BCI Competition,
Track 3.

**Dataset source:** https://osf.io/pq7vb/

The dataset contains EEG recordings corresponding to five
imagined speech classes.

The dataset information supplied for this project describes
15 participants, identified as S1–S15, aged 20–30 years.

## 2. Imagined Speech Classes

| Label | Class name |
|---:|---|
| 0 | Hello |
| 1 | Helpme |
| 2 | Stop |
| 3 | Thankyou |
| 4 | Yes |

Total number of classes: **5**

## 3. Dataset Folder Structure

```text
Imagined_Speech_EEG_Project/
|
|-- dataset/
|   |
|   |-- Training set/
|   |   |-- Data_Sample01.mat
|   |   |-- ...
|   |   |-- Data_Sample15.mat
|   |
|   |-- Validation set/
|   |   |-- Data_Sample01.mat
|   |   |-- ...
|   |   |-- Data_Sample15.mat
|   |
|   |-- Test set/
|       |-- Data_Sample01.mat
|       |-- ...
|       |-- Data_Sample15.mat
|
|-- experiment_outputs/
    |-- Dataset_Documentation/
```

## 4. EEG Signal Characteristics

| Parameter | Value |
|---|---:|
| Sampling frequency | 256 Hz |
| Number of EEG channels | 64 |
| Samples per trial | 795 |
| Approximate duration | {795/256:.4f} seconds |
| Number of classes | 5 |
| Canonical labelled data layout | Trials × Channels × Time |

The Training and Validation files were converted from their
stored MATLAB array order to the canonical order:

`(trials, channels, time_samples)`.

## 5. Dataset Split Summary

| Split | Subjects inspected | Total trials |
|---|---:|---:|
| Training set | {training_subjects} | {training_total} |
| Validation set | {validation_subjects} | {validation_total} |
| Test set | {len(test_summary)} | Not inferred from labels |

## 6. Training Set Class Distribution

| Class | Trials per subject | Total trials |
|---|---:|---:|
| Hello | 60 | {60*training_subjects} |
| Helpme | 60 | {60*training_subjects} |
| Stop | 60 | {60*training_subjects} |
| Thankyou | 60 | {60*training_subjects} |
| Yes | 60 | {60*training_subjects} |

## 7. Validation Set Class Distribution

| Class | Trials per subject | Total trials |
|---|---:|---:|
| Hello | 10 | {10*validation_subjects} |
| Helpme | 10 | {10*validation_subjects} |
| Stop | 10 | {10*validation_subjects} |
| Thankyou | 10 | {10*validation_subjects} |
| Yes | 10 | {10*validation_subjects} |

## 8. Electrode Information

The inspected Training metadata provides the following
{len(first_info['channels'])} electrode names:

{', '.join(first_info['channels'])}

The complete electrode index and name mapping is available
in `electrode_information.csv`.

## 9. Subject-wise Dataset Contents

The file `subject_class_distribution.csv` records the number
of trials for each class in every inspected subject and split.

The file `file_summary.csv` records the dimensions and
sampling frequency for every inspected labelled file.

## 10. Test Dataset File Structure

The inspected Test files use MATLAB v7.3/HDF5 format.

For the first inspected Test file:

- EEG dataset shape: (50, 64, 795)
- Sampling frequency: 256 Hz
- `epo_test/y` shape: (2,)
- `epo_test/y` data type: uint64
- Raw `epo_test/y` values: [0, 0]

The two-element `y` field is not a per-trial label vector
for the 50 EEG trials. Its meaning has not been established.
The test-label contents must therefore not be interpreted
as class labels.

See `test_file_structure.csv` for the structural inspection
of the Test files.

## 11. Dataset Balance

The Training and Validation class distributions were
calculated from the labels in all inspected subject files.

The Training set contains 60 trials per class per subject.
The Validation set contains 10 trials per class per subject.

## 12. MATLAB File Contents

The inspected Training MATLAB variable is `epo_train`.
Its fields include:

- `x`: EEG signal array
- `y`: class label matrix
- `fs`: sampling frequency
- `clab`: channel labels
- `className`: class names
- `t`: time vector
- `title`: subject title
- `file`: file information

The inspected Validation variable is `epo_validation`
with corresponding EEG and metadata fields.

The inspected Test HDF5 group is `epo_test`.

## 13. Documentation Scope

This document describes the dataset and its contents only.

It does not contain:
- EEG preprocessing results
- Wavelet or scalogram results
- Model training
- Classification accuracy
- Model comparisons
- Experimental conclusions

---

**End of Dataset Documentation**
"""

md_file = DOC_DIR / "Dataset_Documentation_Report.md"

with open(md_file, "w", encoding="utf-8") as f:
    f.write(report)

# ------------------------------------------------------------
# 11. SAVE MACHINE-READABLE DATASET METADATA
# ------------------------------------------------------------

metadata = {
    "dataset_name": "Imagined Speech EEG - BCI Competition 2020 Track 3",
    "source": "https://osf.io/pq7vb/",
    "classes": CLASS_NAMES,
    "number_of_classes": NUM_CLASSES,
    "sampling_rate_hz": 256,
    "channels": first_info["channels"],
    "time_samples_per_trial": 795,
    "training_trials_verified": training_total,
    "validation_trials_verified": validation_total,
    "training_subjects_verified": training_subjects,
    "validation_subjects_verified": validation_subjects,
    "test_files_inspected": len(test_summary),
    "documentation_scope": "Dataset description only"
}

with open(DOC_DIR / "dataset_metadata.json", "w") as f:
    json.dump(metadata, f, indent=4)

# ------------------------------------------------------------
# 12. DISPLAY REPORT AND FILE LIST
# ------------------------------------------------------------

display(Markdown(report))

print("\nDOCUMENTATION GENERATED SUCCESSFULLY")
print("=" * 55)

for file in sorted(DOC_DIR.iterdir()):
    print(file.name, "-", round(file.stat().st_size / 1024, 2), "KB")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Dataset directory: /content/drive/MyDrive/Imagined_Speech_EEG_Project/dataset
Documentation directory: /content/drive/MyDrive/Imagined_Speech_EEG_Project/experiment_outputs/Dataset_Documentation

Inspecting: Training set

Inspecting: Validation set

Inspecting: Test set

FILE SUMMARY

,Split,Subject,Trials,Channels,Time samples,Sampling rate (Hz),Original EEG shape,Standardized EEG shape
0,Training set,01,300,64,795,256.0,"(795, 64, 300)","(300, 64, 795)"
1,Training set,02,300,64,795,256.0,"(795, 64, 300)","(300, 64, 795)"
2,Training set,03,300,64,795,256.0,"(795, 64, 300)","(300, 64, 795)"
3,Training set,04,300,64,795,256.0,"(795, 64, 300)","(300, 64, 795)"
4,Training set,05,300,64,795,256.0,"(795, 64, 300)","(300, 64, 795)"
5,Training set,06,300,64,795,256.0,"(795, 64, 300)","(300, 64, 795)"
6,Training set,07,300,64,795,256.0,"(795, 64, 300)","(300, 64, 795)"
7,Training set,08,300,64,795,256.0,"(795, 64, 300)","(300, 64, 795)"
8,Training set,09,300,64,795,256.0,"(795, 64, 300)","(300, 64, 795)"
9,Training set,10,300,64,795,256.0,"(795, 64, 300)","(300, 64, 795)"
10,Training set,11,300,64,795,256.0,"(795, 64, 300)","(300, 64, 795)"
11,Training set,12,300,64,795,256.0,"(795, 64, 300)","(300, 64, 795)"
12,Training set,13,300,64,795,256.0,"(795, 64, 300)","(300, 64, 795)"
13,Training set,14,300,64,795,256.0,"(795, 64, 300)","(300, 64, 795)"
14,Training set,15,300,64,795,256.0,"(795, 64, 300)","(300, 64, 795)"
15,Validation set,01,50,64,795,256.0,"(795, 64, 50)","(50, 64, 795)"
16,Validation set,02,50,64,795,256.0,"(795, 64, 50)","(50, 64, 795)"
17,Validation set,03,50,64,795,256.0,"(795, 64, 50)","(50, 64, 795)"
18,Validation set,04,50,64,795,256.0,"(795, 64, 50)","(50, 64, 795)"
19,Validation set,05,50,64,795,256.0,"(795, 64, 50)","(50, 64, 795)"
20,Validation set,06,50,64,795,256.0,"(795, 64, 50)","(50, 64, 795)"
21,Validation set,07,50,64,795,256.0,"(795, 64, 50)","(50, 64, 795)"
22,Validation set,08,50,64,795,256.0,"(795, 64, 50)","(50, 64, 795)"
23,Validation set,09,50,64,795,256.0,"(795, 64, 50)","(50, 64, 795)"
24,Validation set,10,50,64,795,256.0,"(795, 64, 50)","(50, 64, 795)"
25,Validation set,11,50,64,795,256.0,"(795, 64, 50)","(50, 64, 795)"
26,Validation set,12,50,64,795,256.0,"(795, 64, 50)","(50, 64, 795)"
27,Validation set,13,50,64,795,256.0,"(795, 64, 50)","(50, 64, 795)"
28,Validation set,14,50,64,795,256.0,"(795, 64, 50)","(50, 64, 795)"
29,Validation set,15,50,64,795,256.0,"(795, 64, 50)","(50, 64, 795)"

SUBJECT-WISE CLASS DISTRIBUTION

             Split Subject  Total trials  Hello  Helpme  Stop  Thankyou  Yes
0     Training set      01           300     60      60    60        60   60
1     Training set      02           300     60      60    60        60   60
2     Training set      03           300     60      60    60        60   60
3     Training set      04           300     60      60    60        60   60
4     Training set      05           300     60      60    60        60   60
5     Training set      06           300     60      60    60        60   60
6     Training set      07           300     60      60    60        60   60
7     Training set      08           300     60      60    60        60   60
8     Training set      09           300     60      60    60        60   60
9     Training set      10           300     60      60    60        60   60
10    Training set      11           300     60      60    60        60   60
11    Training set      12           300     60      60    60        60   60
12    Training set      13           300     60      60    60        60   60
13    Training set      14           300     60      60    60        60   60
14    Training set      15           300     60      60    60        60   60
15  Validation set      01            50     10      10    10        10   10
16  Validation set      02            50     10      10    10        10   10
17  Validation set      03            50     10      10    10        10   10
18  Validation set      04            50     10      10    10        10   10
19  Validation set      05            50     10      10    10        10   10
20  Validation set      06            50     10      10    10        10   10
21  Validation set      07            50     10      10    10        10   10
22  Validation set      08            50     10      10    10        10   10
23  Validation set      09            50     10      10    10        10   10
24  Validation set      10            50     10      10    10        10   10
25  Validation set      11            50     10      10    10        10   10
26  Validation set      12            50     10      10    10        10   10
27  Validation set      13            50     10      10    10        10   10
28  Validation set      14            50     10      10    10        10   10
29  Validation set      15            50     10      10    10        10   10

TEST FILE STRUCTURE

,Subject,EEG shape stored in HDF5,Sampling rate (Hz),y shape,y dtype,y raw values,Channel metadata shape,Class metadata shape
0,01,"(50, 64, 795)",256.0,"(2,)",uint64,"[0, 0]","(64, 1)","(5, 1)"
1,02,"(50, 64, 795)",256.0,"(2,)",uint64,"[0, 0]","(64, 1)","(5, 1)"
2,03,"(50, 64, 795)",256.0,"(2,)",uint64,"[0, 0]","(64, 1)","(5, 1)"
3,04,"(50, 64, 795)",256.0,"(2,)",uint64,"[0, 0]","(64, 1)","(5, 1)"
4,05,"(50, 64, 795)",256.0,"(2,)",uint64,"[0, 0]","(64, 1)","(5, 1)"
5,06,"(50, 64, 795)",256.0,"(2,)",uint64,"[0, 0]","(64, 1)","(5, 1)"
6,07,"(50, 64, 795)",256.0,"(2,)",uint64,"[0, 0]","(64, 1)","(5, 1)"
7,08,"(50, 64, 795)",256.0,"(2,)",uint64,"[0, 0]","(64, 1)","(5, 1)"
8,09,"(50, 64, 795)",256.0,"(2,)",uint64,"[0, 0]","(64, 1)","(5, 1)"
9,10,"(50, 64, 795)",256.0,"(2,)",uint64,"[0, 0]","(64, 1)","(5, 1)"
10,11,"(50, 64, 795)",256.0,"(2,)",uint64,"[0, 0]","(64, 1)","(5, 1)"
11,12,"(50, 64, 795)",256.0,"(2,)",uint64,"[0, 0]","(64, 1)","(5, 1)"
12,13,"(50, 64, 795)",256.0,"(2,)",uint64,"[0, 0]","(64, 1)","(5, 1)"
13,14,"(50, 64, 795)",256.0,"(2,)",uint64,"[0, 0]","(64, 1)","(5, 1)"
14,15,"(50, 64, 795)",256.0,"(2,)",uint64,"[0, 0]","(64, 1)","(5, 1)"

OVERALL SUMMARY

,Split,Subjects inspected,Total trials,Channels,Time samples,Sampling rate (Hz)
0,Training set,15,4500,[64],[795],[256.0]
1,Validation set,15,750,[64],[795],[256.0]

OVERALL CLASS DISTRIBUTION

Split     Class  Training set  Validation set
0         Hello           900             150
1        Helpme           900             150
2          Stop           900             150
3      Thankyou           900             150
4           Yes           900             150

ELECTRODE INFORMATION

    Electrode Index Electrode Name
0                 0            Fp1
1                 1            Fp2
2                 2             F7
3                 3             F3
4                 4             Fz
..              ...            ...
59               59            PO7
60               60            PO3
61               61            POz
62               62            PO4
63               63            PO8

[64 rows x 2 columns]

# Imagined Speech EEG Dataset
## Dataset Description and Contents

**Documentation date:** 30 October 2026

---

## 1. Dataset Overview

The dataset used in this project is the Imagined Speech EEG
dataset associated with the 2020 International BCI Competition,
Track 3.

**Dataset source:** https://osf.io/pq7vb/

The dataset contains EEG recordings corresponding to five
imagined speech classes.

The dataset information supplied for this project describes
15 participants, identified as S1–S15, aged 20–30 years.

## 2. Imagined Speech Classes

| Label | Class name |
|---:|---|
| 0 | Hello |
| 1 | Helpme |
| 2 | Stop |
| 3 | Thankyou |
| 4 | Yes |

Total number of classes: **5**

## 3. Dataset Folder Structure

```text
Imagined_Speech_EEG_Project/
|
|-- dataset/
|   |
|   |-- Training set/
|   |   |-- Data_Sample01.mat
|   |   |-- ...
|   |   |-- Data_Sample15.mat
|   |
|   |-- Validation set/
|   |   |-- Data_Sample01.mat
|   |   |-- ...
|   |   |-- Data_Sample15.mat
|   |
|   |-- Test set/
|       |-- Data_Sample01.mat
|       |-- ...
|       |-- Data_Sample15.mat
|
|-- experiment_outputs/
    |-- Dataset_Documentation/
```

## 4. EEG Signal Characteristics

| Parameter | Value |
|---|---:|
| Sampling frequency | 256 Hz |
| Number of EEG channels | 64 |
| Samples per trial | 795 |
| Approximate duration | 3.1055 seconds |
| Number of classes | 5 |
| Canonical labelled data layout | Trials × Channels × Time |

The Training and Validation files were converted from their
stored MATLAB array order to the canonical order:

`(trials, channels, time_samples)`.

## 5. Dataset Split Summary

| Split | Subjects inspected | Total trials |
|---|---:|---:|
| Training set | 15 | 4500 |
| Validation set | 15 | 750 |
| Test set | 15 | Not inferred from labels |

## 6. Training Set Class Distribution

| Class | Trials per subject | Total trials |
|---|---:|---:|
| Hello | 60 | 900 |
| Helpme | 60 | 900 |
| Stop | 60 | 900 |
| Thankyou | 60 | 900 |
| Yes | 60 | 900 |

## 7. Validation Set Class Distribution

| Class | Trials per subject | Total trials |
|---|---:|---:|
| Hello | 10 | 150 |
| Helpme | 10 | 150 |
| Stop | 10 | 150 |
| Thankyou | 10 | 150 |
| Yes | 10 | 150 |

## 8. Electrode Information

The inspected Training metadata provides the following
64 electrode names:

Fp1, Fp2, F7, F3, Fz, F4, F8, FC5, FC1, FC2, FC6, T7, C3, Cz, C4, T8, TP9, CP5, CP1, CP2, CP6, TP10, P7, P3, Pz, P4, P8, PO9, O1, Oz, O2, PO10, AF7, AF3, AF4, AF8, F5, F1, F2, F6, FT9, FT7, FC3, FC4, FT8, FT10, C5, C1, C2, C6, TP7, CP3, CPz, CP4, TP8, P5, P1, P2, P6, PO7, PO3, POz, PO4, PO8

The complete electrode index and name mapping is available
in `electrode_information.csv`.

## 9. Subject-wise Dataset Contents

The file `subject_class_distribution.csv` records the number
of trials for each class in every inspected subject and split.

The file `file_summary.csv` records the dimensions and
sampling frequency for every inspected labelled file.

## 10. Test Dataset File Structure

The inspected Test files use MATLAB v7.3/HDF5 format.

For the first inspected Test file:

- EEG dataset shape: (50, 64, 795)
- Sampling frequency: 256 Hz
- `epo_test/y` shape: (2,)
- `epo_test/y` data type: uint64
- Raw `epo_test/y` values: [0, 0]

The two-element `y` field is not a per-trial label vector
for the 50 EEG trials. Its meaning has not been established.
The test-label contents must therefore not be interpreted
as class labels.

See `test_file_structure.csv` for the structural inspection
of the Test files.

## 11. Dataset Balance

The Training and Validation class distributions were
calculated from the labels in all inspected subject files.

The Training set contains 60 trials per class per subject.
The Validation set contains 10 trials per class per subject.

## 12. MATLAB File Contents

The inspected Training MATLAB variable is `epo_train`.
Its fields include:

- `x`: EEG signal array
- `y`: class label matrix
- `fs`: sampling frequency
- `clab`: channel labels
- `className`: class names
- `t`: time vector
- `title`: subject title
- `file`: file information

The inspected Validation variable is `epo_validation`
with corresponding EEG and metadata fields.

The inspected Test HDF5 group is `epo_test`.

## 13. Documentation Scope

This document describes the dataset and its contents only.

It does not contain:
- EEG preprocessing results
- Wavelet or scalogram results
- Model training
- Classification accuracy
- Model comparisons
- Experimental conclusions

---

**End of Dataset Documentation**

DOCUMENTATION GENERATED SUCCESSFULLY
=======================================================
Dataset_Documentation_Report.md - 4.42 KB
class_distribution_by_subject.csv - 4.17 KB
dataset_metadata.json - 1.48 KB
electrode_information.csv - 0.43 KB
file_summary.csv - 2.05 KB
overall_class_distribution.csv - 0.1 KB
subject_class_distribution.csv - 1.1 KB
test_file_structure.csv - 1.1 KB